packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - protobufjs
